### ISSUE TITLE
Vertical edges should be collapsed in IET creation

### ISSUE THREAD

**Issue by saraedum** [flatsurf/flatsurf#71]
i.e., the other two (rather four) half edges in such faces should be identified.

This changes connected components: two faces are certainly in the same component if they share an edge. (since there's no verticals anymore.)

What's annoying: We need to keep track of where the verticals used to be…it's a bit unclear how exactly.

**Comment by videlec** [comment]
To keep track of the disapearing verticals, one needs to give labels to the (incoming and outgoing) vertical tangent vectors at each vertex in the initial translation surface. These labels can be carried around when doing flip (this is a local operation and depends on the sign of the real part of the newly created edge). When a collapse of a vertical edge occurs we will loose two tangent vectors (an outgoing one and an incoming ones). This is the data that needs to be remembered together with the integral coordinates in terms of the initial flat triangulation (so that we can recover the vertical component of the vector). The rest of the labeling in the surface does not change.

One way to label the tangent vectors is to assign the labels to triangles (there is a bijection between vertical tangent vector and triangles). I used to store this kind of data in an array `half edge -> triangle label`.

**Comment by saraedum** [comment]
Implementing Flow Decomposition #112 I am now coming back to this.

I am not sure this is really such a good idea as a lot of bookkeeping is necessary to make this work. I am getting the feeling that it's easier to just keep track of the chains of vertical edges that separate the components.

One example where I find that this is complicating things a lot is for example something like this (consider this a part of a bigger triangulation i.e. nothing on the boundary is glued here.)

![image](https://user-images.githubusercontent.com/373765/69155053-577dc100-0ae1-11ea-9fee-7102746853ff.png)
After collapsing the yellow faces it would seem that the red edge can be flipped now. But I don't think it can, so we have to keep track of these things.

**Comment by videlec** [comment]
In this example, the red should not be flipped because it is not a large edge. The flip is valid from the point of view of the flat triangulation, but it is not what the algorithm for finding the flow decomposition allows you to do.

**Comment by videlec** [comment]
If the red was large, flipping it in the collapsed triangulation corresponds to multiple flips in the original one.

**Comment by saraedum** [comment]
Collapsing is implemented in `FlatTriangulationCollapsed`.
